export const pricingTiersYT = [
  {
    title: "Ali Abdaal Style",
    monthlyPrice: 15,
    buttonText: "Choose Ali's Style",
    popular: false,
    inverse: false,
    features: [
      "Professional Subtitles",
      "Custom Headings & Text Overlays",
      "High-quality Background Selection",
      "Icon Integration",
      "Strategic B-roll Placement",
      "Dynamic Motion Graphics",
      "Advanced Keyframing",
      "Green Screen Effects",
    ],
  },
  {
    title: "Iman Gadzhi Style",
    monthlyPrice: 20,
    buttonText: "Choose Iman's Style",
    popular: true,
    inverse: true,
    features: [
      "Professional Subtitles",
      "Custom Headings & Text Overlays",
      "Premium Background Selection",
      "Icon Integration",
      "Cinematic B-roll",
      "Advanced Motion Graphics",
      "Complex Keyframing",
      "Professional Green Screen",
      "Custom Animations",
    ],
  },
  {
    title: "Unique Style",
    monthlyPrice: 25,
    buttonText: "Create Your Style",
    popular: false,
    inverse: false,
    features: [
      "Custom Branded Subtitles",
      "Personalized Headings & Branding",
      "Custom Background Design",
      "Custom Icon Package",
      "Premium B-roll Selection",
      "Bespoke Motion Graphics",
      "Advanced Keyframing & Effects",
      "Professional Green Screen",
      "Custom Animation Package",
      "Unlimited Revisions",
    ],
  },
];
