export const pricingTiersAds = [
  {
    title: "Clean",
    monthlyPrice: 40,
    buttonText: "Choose Clean",
    popular: false,
    inverse: false,
    features: ["Headings/text", "Backgrounds", "Icons", "Motion Graphics"],
  },
  {
    title: "Fast and Engaging",
    monthlyPrice: 50,
    buttonText: "Choose Fast and Engaging",
    popular: false,
    inverse: false,
    features: [
      "Subtitles",
      "Headings/text",
      "Backgrounds",
      "Icons",
      "B-roll",
      "Green screen",
    ],
  },
  {
    title: "Unique Style",
    monthlyPrice: 70,
    buttonText: "Choose Unique Style",
    popular: true,
    inverse: true,
    features: [
      "Subtitles",
      "Headings/text",
      "Backgrounds",
      "Icons",
      "B-roll",
      "Motion Graphics",
      "Keyframing",
      "Green screen",
      "Animations",
    ],
  },
];
