export const pricingTiersCurs = [
  {
    title: "Your Style of Choice",
    hourlyRate: 30,
    buttonText: "Choose Your Style",
    popular: false,
    inverse: false,
    features: [
      "Subtitles",
      "Headings/text",
      "Backgrounds",
      "Icons",
      "B-roll",
      "Motion Graphics",
      "Keyframing",
      "Green screen",
      "Animations",
    ],
  },
  {
    title: "Basic Package",
    hourlyRate: 20,
    buttonText: "Choose Basic Package",
    popular: false,
    inverse: false,
    features: ["Subtitles", "Headings/text", "Backgrounds", "Icons"],
  },
  {
    title: "Premium Package",
    hourlyRate: 50,
    buttonText: "Choose Premium Package",
    popular: true,
    inverse: true,
    features: [
      "Subtitles",
      "Headings/text",
      "Backgrounds",
      "Icons",
      "B-roll",
      "Motion Graphics",
      "Keyframing",
      "Green screen",
      "Animations",
      "Custom Branding",
      "Unlimited Revisions",
    ],
  },
];
